- name: user setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: installing python
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

    
- name: starting user service
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml

