- name: user setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: installing java
  ansible.builtin.import_role:
    name: common
    tasks_from: java.yaml

- name: install mysql python libraries
  ansible.builtin.pip:
    executable: pip3.9
    name: "{{ item }}"
  loop:
  - cryptography
  - PyMySQL

- name: import shipping data into mysql
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: "{{ SHIPPING_USER }}"
    login_password: "{{ SHIPPING_PASSWORD }}"
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql
    
- name: starting user service
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml

